name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.0.5
  path_provider: ^2.0.15
  image: ^4.0.17
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png



